Created a Seeder File and name it as UserSeeder
RecruitLab/Recruit-Backend pull request #5
Opened 2023-07-20 09:15 UTC by YANCZY

The following files that has been amended are:
**DatabaseSeeder.php** (database/seeders/DatabaseSeeder.php)
**UserSeeder.php** (database/seeders/UserSeeder.php)

In the UserSeeder I added a script to create a user with random details. And UserSeeder is being called in DatabaseSeeder.

2023-07-20 09:25 UTC, MarJose123 reviewed
missing `UserSeeder`

2023-07-20 09:26 UTC, MarJose123 requested changes
Add the missing `UserSeeder` Class

2023-07-21 02:58 UTC, YANCZY commented
I have added the UserSeeder into the commit.

Please also see the following files I have added

RoleSeeder - For Roles and Permission
Kernel - Add a middleware package of spatie

Also in the password of user is password 123 and everything else is we're using faker library.

2023-07-21 09:52 UTC, MarJose123 commented on config/app.php
Not needed, please remove.

2023-07-21 09:54 UTC, MarJose123 requested changes
Please remove the `  Spatie\Permission\PermissionServiceProvider::class,` in the `config/app.php`

2023-07-21 09:59 UTC, MarJose123 approved these changes

2023-07-21 09:59 UTC, merged